### ISSUE TITLE
Assetion Error opening a valid PSD 

### ISSUE THREAD

**Issue by nico00** [psd-tools/psd-tools#316]
**Description**
Opening the attached PSD file with psd-tools, it raises an AssetionError.
Opening the same file with Photoshop it seems everything is ok.

**File to test**
[error.psd.zip](https://github.com/psd-tools/psd-tools/files/8728341/error.psd.zip)

**Version**
psd-tools: 1.9.20
Python: 3.8.12

**Comment by kyamagu** [comment]
Ok, the file is indeed broken. The internal data structure is not well formatted. I suspect the file is generated outside of Adobe Photoshop, since the image resources section is almost empty. In what tool is this file made?

Anyway, I will implement a workaround so that at least `psd-tools` does not crash.

**Comment by nico00** [comment]
I confirm it has been generated using Wand. Usually PSDs generated by Wand work properly, but there are some cases where this not happen. Probably a bug in Wand. 
I have to use Wand because, as far as I know, psd-tools is not able to generate a multi-layer PSD.

Exactly what is the problem in the PSD ? I could patch the file after Wand and before psd-tools.

Said that, I noticed that forcing psd-tools to continue (by commenting the assert line), it opens the PSD properly.
