### ISSUE TITLE
Error and Corruption When Reopening PSD Files Saved with psd-tools

### ISSUE THREAD

**Issue by magurotaisa** [psd-tools/psd-tools#372]
**Describe the bug**
When attempting to reopen a psd file saved using psd-tools, an error occurs, preventing successful reopening.

**To Reproduce**

1. Open a PSD file using psd-tools, e.g., "error_sample.psd".
2. Save the opened PSD file as "sample.psd" using the following code in Python:
```python
psd = PSDImage.open("error_sample.psd")
psd.save("sample.psd")
```
3. Try to reopen "sample.psd" using psd-tools with the following code in Python:
```python
PSDImage.open("sample.psd")
```

**Expected behavior**
Both "error_sample.psd" and "sample.psd" should be identical, and "sample.psd" should be successfully reopened without any errors.

**File and screenshots**
Error file: 
[error_sample.psd.zip](https://github.com/psd-tools/psd-tools/files/12213564/error_sample.psd.zip)

Error log:
```
File ~/.pyenv/versions/3.8.10/lib/python3.8/enum.py:663, in Enum.__new__(cls, value)
    661 ve_exc = ValueError("%r is not a valid %s" % (value, cls.__name__))
    662 if result is None and exc is None:
--> 663     raise ve_exc
    664 elif exc is None:
    665     exc = TypeError(
    666             'error in %s._missing_: returned %r instead of None or a valid member'
    667             % (cls.__name__, result)
    668             )

ValueError: b'loat' is not a valid OSType
```

**Environment**
 - Python [3.8.10]
 - Version [v1.9.28]

**Additional context**
After investigating the issue,  it has been discovered that the error occurs when there are layers that require clipping during the Lab to RGB conversion process.

**Comment by kyamagu** [comment]
This is likely a bug in the low-level psd structure

**Comment by oh-ok** [comment]
Found the cause of this. It affected every PSD that contained a SolidColor layer.

The `redFloat`, `blueFloat` and `greenFloat` keys are being interpreted as OSTypes since they're in this `_TERMS` set: 

https://github.com/psd-tools/psd-tools/blob/03a14e2c9b9b7e67931f3fb6af4858d29cd42e0a/src/psd_tools/psd/descriptor.py#L69-L77

Since those are the only keys with length greater than 4 (at least at the moment) you can just add a condition to only include length 4 byte strings to fix this, or move the keys to their own separate class.

https://github.com/psd-tools/psd-tools/blob/03a14e2c9b9b7e67931f3fb6af4858d29cd42e0a/src/psd_tools/psd/descriptor.py#L52-L56
